baseURL = "https://example.com"
languageCode = "en-us"
title = "lfkdsk's Blog"
theme = "techo"
DefaultContentLanguage = "en"

[author]
  name = "lfkdsk"
  homepage = "https://lfkdsk.github.io/"
  github = "https://github.com/lfkdsk"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[params]
disqus = "lfkdsk" # disqus account name
extraHead = ''

[[params.socials]]
name = "About Me"
link = "https://github.com/lfkdsk"
